version: '3.8'

services:
  web:
    build:
      context: ./
    container_name: kounda
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=bd_kounda
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bd_kounda
      - TZ=UTC
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
